/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ReturnsRulesRouteImport } from './routes/returns/rules'
import { Route as PaymentResultRouteImport } from './routes/payment/result'
import { Route as DashboardWalletRouteImport } from './routes/dashboard/wallet'
import { Route as DashboardReturnsRouteImport } from './routes/dashboard/returns'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardOrderIdRouteImport } from './routes/dashboard/$orderId'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as GamesSlugIndexRouteImport } from './routes/games/$slug/index'
import { Route as DashboardGamesIndexRouteImport } from './routes/dashboard/games/index'
import { Route as AdminReturnsIndexRouteImport } from './routes/admin/returns/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminGamesIndexRouteImport } from './routes/admin/games/index'
import { Route as AdminReturnsIdRouteImport } from './routes/admin/returns/$id'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as AdminGamesPricingRouteImport } from './routes/admin/games/pricing'
import { Route as AdminGamesNewRouteImport } from './routes/admin/games/new'
import { Route as DashboardGamesItemIdReturnRouteImport } from './routes/dashboard/games/$itemId/return'
import { Route as AdminGamesIdEditRouteImport } from './routes/admin/games/$id/edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRulesRoute = ReturnsRulesRouteImport.update({
  id: '/returns/rules',
  path: '/returns/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment/result',
  path: '/payment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReturnsRoute = DashboardReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrderIdRoute = DashboardOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GamesSlugIndexRoute = GamesSlugIndexRouteImport.update({
  id: '/games/$slug/',
  path: '/games/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGamesIndexRoute = DashboardGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminReturnsIndexRoute = AdminReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamesIndexRoute = AdminGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReturnsIdRoute = AdminReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamesPricingRoute = AdminGamesPricingRouteImport.update({
  id: '/games/pricing',
  path: '/games/pricing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGamesNewRoute = AdminGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardGamesItemIdReturnRoute =
  DashboardGamesItemIdReturnRouteImport.update({
    id: '/games/$itemId/return',
    path: '/games/$itemId/return',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AdminGamesIdEditRoute = AdminGamesIdEditRouteImport.update({
  id: '/games/$id/edit',
  path: '/games/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/dashboard/$orderId': typeof DashboardOrderIdRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/payment/result': typeof PaymentResultRoute
  '/returns/rules': typeof ReturnsRulesRoute
  '/auth/': typeof AuthIndexRoute
  '/cart/': typeof CartIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/games/pricing': typeof AdminGamesPricingRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/returns/$id': typeof AdminReturnsIdRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/returns/': typeof AdminReturnsIndexRoute
  '/dashboard/games/': typeof DashboardGamesIndexRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
  '/dashboard/games/$itemId/return': typeof DashboardGamesItemIdReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/dashboard/$orderId': typeof DashboardOrderIdRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/payment/result': typeof PaymentResultRoute
  '/returns/rules': typeof ReturnsRulesRoute
  '/auth': typeof AuthIndexRoute
  '/cart': typeof CartIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/games': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/games/pricing': typeof AdminGamesPricingRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/returns/$id': typeof AdminReturnsIdRoute
  '/admin/games': typeof AdminGamesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/returns': typeof AdminReturnsIndexRoute
  '/dashboard/games': typeof DashboardGamesIndexRoute
  '/games/$slug': typeof GamesSlugIndexRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
  '/dashboard/games/$itemId/return': typeof DashboardGamesItemIdReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/dashboard/$orderId': typeof DashboardOrderIdRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/returns': typeof DashboardReturnsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/payment/result': typeof PaymentResultRoute
  '/returns/rules': typeof ReturnsRulesRoute
  '/auth/': typeof AuthIndexRoute
  '/cart/': typeof CartIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/games/pricing': typeof AdminGamesPricingRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/returns/$id': typeof AdminReturnsIdRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/returns/': typeof AdminReturnsIndexRoute
  '/dashboard/games/': typeof DashboardGamesIndexRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
  '/dashboard/games/$itemId/return': typeof DashboardGamesItemIdReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/audit'
    | '/dashboard/$orderId'
    | '/dashboard/profile'
    | '/dashboard/returns'
    | '/dashboard/wallet'
    | '/payment/result'
    | '/returns/rules'
    | '/auth/'
    | '/cart/'
    | '/dashboard/'
    | '/games/'
    | '/admin/games/new'
    | '/admin/games/pricing'
    | '/admin/orders/$orderId'
    | '/admin/returns/$id'
    | '/admin/games/'
    | '/admin/orders/'
    | '/admin/returns/'
    | '/dashboard/games/'
    | '/games/$slug/'
    | '/admin/games/$id/edit'
    | '/dashboard/games/$itemId/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/audit'
    | '/dashboard/$orderId'
    | '/dashboard/profile'
    | '/dashboard/returns'
    | '/dashboard/wallet'
    | '/payment/result'
    | '/returns/rules'
    | '/auth'
    | '/cart'
    | '/dashboard'
    | '/games'
    | '/admin/games/new'
    | '/admin/games/pricing'
    | '/admin/orders/$orderId'
    | '/admin/returns/$id'
    | '/admin/games'
    | '/admin/orders'
    | '/admin/returns'
    | '/dashboard/games'
    | '/games/$slug'
    | '/admin/games/$id/edit'
    | '/dashboard/games/$itemId/return'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/audit'
    | '/dashboard/$orderId'
    | '/dashboard/profile'
    | '/dashboard/returns'
    | '/dashboard/wallet'
    | '/payment/result'
    | '/returns/rules'
    | '/auth/'
    | '/cart/'
    | '/dashboard/'
    | '/games/'
    | '/admin/games/new'
    | '/admin/games/pricing'
    | '/admin/orders/$orderId'
    | '/admin/returns/$id'
    | '/admin/games/'
    | '/admin/orders/'
    | '/admin/returns/'
    | '/dashboard/games/'
    | '/games/$slug/'
    | '/admin/games/$id/edit'
    | '/dashboard/games/$itemId/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PaymentResultRoute: typeof PaymentResultRoute
  ReturnsRulesRoute: typeof ReturnsRulesRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GamesSlugIndexRoute: typeof GamesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/rules': {
      id: '/returns/rules'
      path: '/returns/rules'
      fullPath: '/returns/rules'
      preLoaderRoute: typeof ReturnsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/result': {
      id: '/payment/result'
      path: '/payment/result'
      fullPath: '/payment/result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/returns': {
      id: '/dashboard/returns'
      path: '/returns'
      fullPath: '/dashboard/returns'
      preLoaderRoute: typeof DashboardReturnsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$orderId': {
      id: '/dashboard/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/$orderId'
      preLoaderRoute: typeof DashboardOrderIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/games/$slug/': {
      id: '/games/$slug/'
      path: '/games/$slug'
      fullPath: '/games/$slug/'
      preLoaderRoute: typeof GamesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/games/': {
      id: '/dashboard/games/'
      path: '/games'
      fullPath: '/dashboard/games/'
      preLoaderRoute: typeof DashboardGamesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/returns/': {
      id: '/admin/returns/'
      path: '/returns'
      fullPath: '/admin/returns/'
      preLoaderRoute: typeof AdminReturnsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/games/': {
      id: '/admin/games/'
      path: '/games'
      fullPath: '/admin/games/'
      preLoaderRoute: typeof AdminGamesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/returns/$id': {
      id: '/admin/returns/$id'
      path: '/returns/$id'
      fullPath: '/admin/returns/$id'
      preLoaderRoute: typeof AdminReturnsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/games/pricing': {
      id: '/admin/games/pricing'
      path: '/games/pricing'
      fullPath: '/admin/games/pricing'
      preLoaderRoute: typeof AdminGamesPricingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/games/new': {
      id: '/admin/games/new'
      path: '/games/new'
      fullPath: '/admin/games/new'
      preLoaderRoute: typeof AdminGamesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/games/$itemId/return': {
      id: '/dashboard/games/$itemId/return'
      path: '/games/$itemId/return'
      fullPath: '/dashboard/games/$itemId/return'
      preLoaderRoute: typeof DashboardGamesItemIdReturnRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/games/$id/edit': {
      id: '/admin/games/$id/edit'
      path: '/games/$id/edit'
      fullPath: '/admin/games/$id/edit'
      preLoaderRoute: typeof AdminGamesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminGamesNewRoute: typeof AdminGamesNewRoute
  AdminGamesPricingRoute: typeof AdminGamesPricingRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminReturnsIdRoute: typeof AdminReturnsIdRoute
  AdminGamesIndexRoute: typeof AdminGamesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminReturnsIndexRoute: typeof AdminReturnsIndexRoute
  AdminGamesIdEditRoute: typeof AdminGamesIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminGamesNewRoute: AdminGamesNewRoute,
  AdminGamesPricingRoute: AdminGamesPricingRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminReturnsIdRoute: AdminReturnsIdRoute,
  AdminGamesIndexRoute: AdminGamesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminReturnsIndexRoute: AdminReturnsIndexRoute,
  AdminGamesIdEditRoute: AdminGamesIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardOrderIdRoute: typeof DashboardOrderIdRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReturnsRoute: typeof DashboardReturnsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGamesIndexRoute: typeof DashboardGamesIndexRoute
  DashboardGamesItemIdReturnRoute: typeof DashboardGamesItemIdReturnRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrderIdRoute: DashboardOrderIdRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReturnsRoute: DashboardReturnsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGamesIndexRoute: DashboardGamesIndexRoute,
  DashboardGamesItemIdReturnRoute: DashboardGamesItemIdReturnRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PaymentResultRoute: PaymentResultRoute,
  ReturnsRulesRoute: ReturnsRulesRoute,
  AuthIndexRoute: AuthIndexRoute,
  CartIndexRoute: CartIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  GamesSlugIndexRoute: GamesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
