/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PaymentResultRouteImport } from './routes/payment/result'
import { Route as DashboardOrderIdRouteImport } from './routes/dashboard/$orderId'
import { Route as GamesIdIndexRouteImport } from './routes/games/$id/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminGamesIndexRouteImport } from './routes/admin/games/index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as AdminGamesNewRouteImport } from './routes/admin/games/new'
import { Route as AdminGamesIdEditRouteImport } from './routes/admin/games/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment/result',
  path: '/payment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrderIdRoute = DashboardOrderIdRouteImport.update({
  id: '/dashboard/$orderId',
  path: '/dashboard/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdIndexRoute = GamesIdIndexRouteImport.update({
  id: '/games/$id/',
  path: '/games/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGamesIndexRoute = AdminGamesIndexRouteImport.update({
  id: '/admin/games/',
  path: '/admin/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGamesNewRoute = AdminGamesNewRouteImport.update({
  id: '/admin/games/new',
  path: '/admin/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGamesIdEditRoute = AdminGamesIdEditRouteImport.update({
  id: '/admin/games/$id/edit',
  path: '/admin/games/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$orderId': typeof DashboardOrderIdRoute
  '/payment/result': typeof PaymentResultRoute
  '/auth/': typeof AuthIndexRoute
  '/cart/': typeof CartIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/games/$id/': typeof GamesIdIndexRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$orderId': typeof DashboardOrderIdRoute
  '/payment/result': typeof PaymentResultRoute
  '/auth': typeof AuthIndexRoute
  '/cart': typeof CartIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/games': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/games': typeof AdminGamesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/games/$id': typeof GamesIdIndexRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/$orderId': typeof DashboardOrderIdRoute
  '/payment/result': typeof PaymentResultRoute
  '/auth/': typeof AuthIndexRoute
  '/cart/': typeof CartIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/games/$id/': typeof GamesIdIndexRoute
  '/admin/games/$id/edit': typeof AdminGamesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/$orderId'
    | '/payment/result'
    | '/auth/'
    | '/cart/'
    | '/dashboard/'
    | '/games/'
    | '/admin/games/new'
    | '/admin/orders/$orderId'
    | '/admin/games/'
    | '/admin/orders/'
    | '/games/$id/'
    | '/admin/games/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$orderId'
    | '/payment/result'
    | '/auth'
    | '/cart'
    | '/dashboard'
    | '/games'
    | '/admin/games/new'
    | '/admin/orders/$orderId'
    | '/admin/games'
    | '/admin/orders'
    | '/games/$id'
    | '/admin/games/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard/$orderId'
    | '/payment/result'
    | '/auth/'
    | '/cart/'
    | '/dashboard/'
    | '/games/'
    | '/admin/games/new'
    | '/admin/orders/$orderId'
    | '/admin/games/'
    | '/admin/orders/'
    | '/games/$id/'
    | '/admin/games/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardOrderIdRoute: typeof DashboardOrderIdRoute
  PaymentResultRoute: typeof PaymentResultRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  AdminGamesNewRoute: typeof AdminGamesNewRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminGamesIndexRoute: typeof AdminGamesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  GamesIdIndexRoute: typeof GamesIdIndexRoute
  AdminGamesIdEditRoute: typeof AdminGamesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/result': {
      id: '/payment/result'
      path: '/payment/result'
      fullPath: '/payment/result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orderId': {
      id: '/dashboard/$orderId'
      path: '/dashboard/$orderId'
      fullPath: '/dashboard/$orderId'
      preLoaderRoute: typeof DashboardOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/': {
      id: '/games/$id/'
      path: '/games/$id'
      fullPath: '/games/$id/'
      preLoaderRoute: typeof GamesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/games/': {
      id: '/admin/games/'
      path: '/admin/games'
      fullPath: '/admin/games/'
      preLoaderRoute: typeof AdminGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/games/new': {
      id: '/admin/games/new'
      path: '/admin/games/new'
      fullPath: '/admin/games/new'
      preLoaderRoute: typeof AdminGamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/games/$id/edit': {
      id: '/admin/games/$id/edit'
      path: '/admin/games/$id/edit'
      fullPath: '/admin/games/$id/edit'
      preLoaderRoute: typeof AdminGamesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardOrderIdRoute: DashboardOrderIdRoute,
  PaymentResultRoute: PaymentResultRoute,
  AuthIndexRoute: AuthIndexRoute,
  CartIndexRoute: CartIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  AdminGamesNewRoute: AdminGamesNewRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminGamesIndexRoute: AdminGamesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  GamesIdIndexRoute: GamesIdIndexRoute,
  AdminGamesIdEditRoute: AdminGamesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
